name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    # add image version back when wpilib 2023 comes out of beta
    container: wpilib/roborio-cross-ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run spotless style checker
      run: ./gradlew spotlessCheck

    - name: Compile and run tests on robot code
      run: ./gradlew build
